# Generated by Django 4.2.15 on 2024-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='min_value',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
    ]
